name: Zygno Data Transformer

on:
  push:
    paths:
      - 'raw_csv/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install pandas
      - name: Ejecutar script
        run: python transformar_sorteos.py
      - name: Commit y Push
        run: |
          git config --global user.name 'Zygno Bot'
          git config --global user.email 'bot@zygno.com'
          git add docs/*.json
          git commit -m "Update JSON in docs: $(date)" || echo "Sin cambios"
          git push
